{{- if .Values.rbac.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-red.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
      {{- include "node-red.labels" . | nindent 4 }}
rules:
  {{- if .Values.clusterRoleRules.enabled }}
    {{- toYaml .Values.clusterRoleRules.rules | nindent 2 }}
  {{- else }}
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  {{- end }}
{{- end }}
