apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-red.fullname" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "node-red.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node-red.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-red.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if or .Values.persistence.enabled .Values.initContainers  }}
      initContainers:
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      - name: permission-fix
        image: busybox
        command: ['sh', '-c']
        args: ['chmod -R 777 /data']
        volumeMounts:
          - name: data
            mountPath: /data
            {{- if .Values.persistence.subPath}}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
      {{- end }}
      {{- end }}
      containers:
        {{- if .Values.sidecars }}
        {{- with .Values.sidecars }}
          {{- toYaml . | nindent  8 }}
        {{- end }}
        {{- end}}
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
          {{- toYaml .Values.env | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- if and .Values.npmrc.enabled }}
            - name: npmrc-volume
              mountPath: /usr/src/node-red/.npmrc
              subPath: npmrc
            {{- end }}
            {{- if .Values.settings }}
            - name: {{ .Values.settings.name }}
              mountPath: /data/settings.js
              subPath: settings.js
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: data
              mountPath: /data
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.npmrc.enabled }}
        - name: npmrc-volume
          configMap:
            name: {{ include "node-red.configMapName" . }}
        {{- end }}
        {{- if .Values.settings }}
        - name: {{ .Values.settings.name }}
          configMap:
            name: {{ .Values.settings.configMapName }}
        {{- end }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "node-red.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: {}
          {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
