{{- if .Values.sidecar.enabled }}
apiVersion: v1
data:
  flow_refresh.py: | {{ range $.Files.Lines "scripts/flow_refresh.py" }}
    {{ . }}{{ end }}
  {{- if .Values.sidecar.extraNodeModules }}
  extra-node-modules.json: |-
    {{ toJson .Values.sidecar.extraNodeModules }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ include "node-red.sidecarConfigMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ .Values.sidecar.env.label}}: {{ .Values.sidecar.env.label_value | quote}}
{{- end }}
